apiVersion: v1
kind: Pod
metadata:
  name: hello-skaffold
  labels:
    app: hello-skaffold
spec:
  containers:
  - name: hello-skaffold
    image: soumiyajit/hello-skaffold
---
apiVersion: v1
kind: Service
metadata:
  name: hello-skaffold
spec:
  selector:
    app: hello-skaffold
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32111
