apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ['/bin/sh', '-c', 'echo -e "<h1>RDS has been verified successfully</h1>" >> /usr/share/nginx/html/index.html;']
        ports:
        - containerPort: 80

