kind: Service
apiVersion: v1
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
