apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aks-storageclass-1
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true  
parameters:
  storageaccounttype: Premium_LRS 
  kind: managed 
reclaimPolicy: Retain  
