apiVersion: v1
kind: Pod
metadata:
  labels:
    run: affinity-pod
    purpose: dev
  name: affinity-pod
spec:
  containers:
  - image: httpd
    name: affinity-pod
  nodeSelector:
    kubernetes.io/hostname: k8s-worker1
