apiVersion: v1
kind: Pod
metadata:
  labels:
    run: antiaffinity-pod
    sre: staging
  name: antiaffinity-pod
spec:
  containers:
  - image: httpd
    name: antiaffinity-pod
  nodeSelector:
    kubernetes.io/hostname: k8s-worker2
