apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    app: httpd
    env: dev
spec:
  containers:
  - image: nginx
    name: test-label
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    app: nginx
    env: prod
spec:
  containers:
  - image: nginx
    name: test-label
