apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-app
  name: redis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - image: redis
        name: redis
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8secret
                key: username
                optional: false
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8secret
                key: password
                optional: false
