apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-selector
spec:
  selector:
    matchLabels:
      run: test-selector
  replicas: 1
  template:
    metadata:
      labels:
        run: test-selector
    spec:
      containers:
      - name: test-selector
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-selector
  labels:
    run: test-selector
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: test-selector
