apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-sc-3
  name: busybox-sc-3
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: busybox-sc-3
    resources: {}
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
