apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-sc-1
  name: busybox-sc-1
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: busybox-sc-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
