apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod-sec-adm
  name: test-pod-sec-adm
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: test-pod-sec-adm
    securityContext:
      allowPrivilegeEscalation: true
