---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: initdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: busybox-container
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo '<html><h1>Verifying Flux Installation</h1>' >> /init-dir/index.html"]
        volumeMounts:
        - name: initdir
          mountPath: "/init-dir"
      volumes:
      - name: initdir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: service-webapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
