apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-rl.yaml
  name: deployment-rl.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-rl.yaml
  template:
    metadata:
      labels:
        app: deployment-rl.yaml
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
