apiVersion: v1
kind: Pod
metadata:
  name: httpd-readiness-probe
spec:
  containers:
  - name: httpd
    image: httpd
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
