apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ts-demo
  name: ts-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ts-demo
  template:
    metadata:
      labels:
        app: ts-demo
    spec:
      containers:
      - image: nginx
        name: nginx
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: ts-demo
