apiVersion: v1
kind: Pod
metadata:
  name: preinstall-hook
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
  - name: prehook-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo DevOps pre-install hook with delete policy && sleep 20' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
