apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      serviceAccountName: k8s-sa
      containers:
        - name: wordpress
          image: wordpress:4.8-apache
          ports:
          - containerPort: 80
            name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: "127.0.0.1"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo1-sql-secret
                  key: password
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo1-sql-secret
                  key: username
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: demo1-sql-secret
                  key: database
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            - "/cloud_sql_proxy"
            - "-instances=gke-mastering-devops:europe-west1:demo1-mysql=tcp:3306"
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: aks-mysql-pv-claim
