apiVersion: v1
kind: Pod
metadata:
  name: preinstall-hook1
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-3"
spec:
  containers:
  - name: prehook-container1
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo DevOps pre-install hook1 && sleep 20' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
