apiVersion: v1
kind: Pod
metadata:
  name: preinstall-hook2
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
spec:
  containers:
  - name: prehook-container2
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo DevOps pre-install hook2 && sleep 20' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
