apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:  
    metadata:
      labels: 
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: initdir
            mountPath: /usr/share/nginx/html
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webapptest"            
            - name: DB_USERNAME
              value: "admin"     
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_ROOT_PASSWORD
      initContainers:
      - name: init-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "<h1>Verified the RDS and accessing from ClassicLB</h1>" >> /init-dir/index.html;']
        volumeMounts:
        - name: initdir
          mountPath: "/init-dir"
      volumes:
      - name: initdir
        emptyDir: {}
